// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package sample_package_0412

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Zhaoh0412Client is the client API for Zhaoh0412 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Zhaoh0412Client interface {
	Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
	Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type zhaoh0412Client struct {
	cc grpc.ClientConnInterface
}

func NewZhaoh0412Client(cc grpc.ClientConnInterface) Zhaoh0412Client {
	return &zhaoh0412Client{cc}
}

func (c *zhaoh0412Client) Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, "/sample_module_0412.sample_package_0412.Zhaoh0412/Heathcheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zhaoh0412Client) Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/sample_module_0412.sample_package_0412.Zhaoh0412/Helloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Zhaoh0412Server is the server API for Zhaoh0412 service.
// All implementations must embed UnimplementedZhaoh0412Server
// for forward compatibility
type Zhaoh0412Server interface {
	Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
	Helloworld(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedZhaoh0412Server()
}

// UnimplementedZhaoh0412Server must be embedded to have forward compatible implementations.
type UnimplementedZhaoh0412Server struct {
}

func (UnimplementedZhaoh0412Server) Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heathcheck not implemented")
}
func (UnimplementedZhaoh0412Server) Helloworld(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Helloworld not implemented")
}
func (UnimplementedZhaoh0412Server) mustEmbedUnimplementedZhaoh0412Server() {}

// UnsafeZhaoh0412Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Zhaoh0412Server will
// result in compilation errors.
type UnsafeZhaoh0412Server interface {
	mustEmbedUnimplementedZhaoh0412Server()
}

func RegisterZhaoh0412Server(s grpc.ServiceRegistrar, srv Zhaoh0412Server) {
	s.RegisterService(&Zhaoh0412_ServiceDesc, srv)
}

func _Zhaoh0412_Heathcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Zhaoh0412Server).Heathcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample_module_0412.sample_package_0412.Zhaoh0412/Heathcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Zhaoh0412Server).Heathcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zhaoh0412_Helloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Zhaoh0412Server).Helloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample_module_0412.sample_package_0412.Zhaoh0412/Helloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Zhaoh0412Server).Helloworld(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Zhaoh0412_ServiceDesc is the grpc.ServiceDesc for Zhaoh0412 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Zhaoh0412_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sample_module_0412.sample_package_0412.Zhaoh0412",
	HandlerType: (*Zhaoh0412Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heathcheck",
			Handler:    _Zhaoh0412_Heathcheck_Handler,
		},
		{
			MethodName: "Helloworld",
			Handler:    _Zhaoh0412_Helloworld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Zhaoh0412.proto",
}
