// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package sample_package_0412

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Zhaoh0412AabbClient is the client API for Zhaoh0412Aabb service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Zhaoh0412AabbClient interface {
	Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
	Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type zhaoh0412AabbClient struct {
	cc grpc.ClientConnInterface
}

func NewZhaoh0412AabbClient(cc grpc.ClientConnInterface) Zhaoh0412AabbClient {
	return &zhaoh0412AabbClient{cc}
}

func (c *zhaoh0412AabbClient) Heathcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, "/sample_module_0412.sample_package_0412.Zhaoh0412aabb/Heathcheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zhaoh0412AabbClient) Helloworld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/sample_module_0412.sample_package_0412.Zhaoh0412aabb/Helloworld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Zhaoh0412AabbServer is the server API for Zhaoh0412Aabb service.
// All implementations must embed UnimplementedZhaoh0412AabbServer
// for forward compatibility
type Zhaoh0412AabbServer interface {
	Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
	Helloworld(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedZhaoh0412AabbServer()
}

// UnimplementedZhaoh0412AabbServer must be embedded to have forward compatible implementations.
type UnimplementedZhaoh0412AabbServer struct {
}

func (UnimplementedZhaoh0412AabbServer) Heathcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heathcheck not implemented")
}
func (UnimplementedZhaoh0412AabbServer) Helloworld(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Helloworld not implemented")
}
func (UnimplementedZhaoh0412AabbServer) mustEmbedUnimplementedZhaoh0412AabbServer() {}

// UnsafeZhaoh0412AabbServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Zhaoh0412AabbServer will
// result in compilation errors.
type UnsafeZhaoh0412AabbServer interface {
	mustEmbedUnimplementedZhaoh0412AabbServer()
}

func RegisterZhaoh0412AabbServer(s grpc.ServiceRegistrar, srv Zhaoh0412AabbServer) {
	s.RegisterService(&Zhaoh0412Aabb_ServiceDesc, srv)
}

func _Zhaoh0412Aabb_Heathcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Zhaoh0412AabbServer).Heathcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample_module_0412.sample_package_0412.Zhaoh0412aabb/Heathcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Zhaoh0412AabbServer).Heathcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Zhaoh0412Aabb_Helloworld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Zhaoh0412AabbServer).Helloworld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample_module_0412.sample_package_0412.Zhaoh0412aabb/Helloworld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Zhaoh0412AabbServer).Helloworld(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Zhaoh0412Aabb_ServiceDesc is the grpc.ServiceDesc for Zhaoh0412Aabb service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Zhaoh0412Aabb_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sample_module_0412.sample_package_0412.Zhaoh0412aabb",
	HandlerType: (*Zhaoh0412AabbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heathcheck",
			Handler:    _Zhaoh0412Aabb_Heathcheck_Handler,
		},
		{
			MethodName: "Helloworld",
			Handler:    _Zhaoh0412Aabb_Helloworld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Zhaoh0412aabb.proto",
}
